import type { WorkBundle } from '../types';

/**
 * Технологические наборы — «подсказки» для замерщика.
 * Работы, которые не делаются одна без другой, собраны в цепочки:
 * выбрал набор → все строки упали в смету с автоматическим объёмом.
 */
export const SEED_BUNDLES: Omit<WorkBundle, 'id'>[] = [
  {
    title: 'Стены: штукатурка по маякам',
    description: 'Грунтовка → маяки → штукатурка. Штукатурка без маяков не принимается по геометрии.',
    stage: 'rough',
    surface: 'walls',
    items: [
      { code: '07.01' },
      { code: '07.02' },
      { code: '07.03' },
      { code: '07.11', optional: true },
    ],
    tags: ['стены', 'черновая'],
  },
  {
    title: 'Стены под покраску (финиш)',
    description: 'Грунтовка → шпаклёвка 2 слоя → ошкуривание → грунт → покраска.',
    stage: 'finishing',
    surface: 'walls',
    items: [
      { code: '07.01' },
      { code: '07.04' },
      { code: '07.05' },
      { code: '07.06', optional: true },
      { code: '07.08' },
    ],
    tags: ['стены', 'чистовая', 'покраска'],
  },
  {
    title: 'Стены под обои',
    description: 'Грунтовка → шпаклёвка → ошкуривание → оклейка обоями.',
    stage: 'finishing',
    surface: 'walls',
    items: [
      { code: '07.01' },
      { code: '07.04' },
      { code: '07.05' },
      { code: '07.07' },
    ],
    tags: ['стены', 'чистовая', 'обои'],
  },
  {
    title: 'Пол: стяжка по маякам',
    description: 'Грунтовка пола → демпферная лента → маяки → стяжка.',
    stage: 'rough',
    surface: 'floor',
    items: [
      { code: '03.01' },
      { code: '03.05' },
      { code: '03.02' },
      { code: '03.03' },
      { code: '03.07', optional: true },
    ],
    tags: ['пол', 'черновая'],
  },
  {
    title: 'Пол: наливной под ламинат',
    description: 'Грунтовка → наливной пол → укладка ламината → плинтус.',
    stage: 'finishing',
    surface: 'floor',
    items: [
      { code: '03.01' },
      { code: '03.08' },
      { code: '08.01' },
      { code: '11.03' },
    ],
    tags: ['пол', 'чистовая', 'ламинат'],
  },
  {
    title: 'Потолок под покраску',
    description: 'Грунтовка → шпаклёвка → ошкуривание → покраска.',
    stage: 'finishing',
    surface: 'ceiling',
    items: [
      { code: '04.01' },
      { code: '09.01' },
      { code: '09.02' },
      { code: '09.03' },
    ],
    tags: ['потолок', 'чистовая'],
  },
  {
    title: 'Потолок ГКЛ',
    description: 'Каркас → обшивка ГКЛ → шпаклёвка → ошкуривание → покраска.',
    stage: 'finishing',
    surface: 'ceiling',
    items: [
      { code: '04.03' },
      { code: '04.04' },
      { code: '09.01' },
      { code: '09.02' },
      { code: '09.03' },
    ],
    tags: ['потолок', 'ГКЛ'],
  },
  {
    title: 'Санузел под ключ (черновой этап)',
    description: 'Гидроизоляция, стяжка, штукатурка стен, разводка сантехники.',
    stage: 'rough',
    surface: 'rooms',
    items: [
      { code: '07.01', factor: 1 },
      { code: '07.02' },
      { code: '07.03' },
      { code: '03.01' },
      { code: '03.06' },
      { code: '03.02' },
      { code: '03.03' },
      { code: '06.01' },
      { code: '06.02' },
    ],
    tags: ['санузел', 'черновая'],
  },
  {
    title: 'Санузел: плитка',
    description: 'Плитка на стены и пол, затирка, запил 45°, ревизионный люк.',
    stage: 'finishing',
    surface: 'rooms',
    items: [
      { code: '10.01' },
      { code: '10.03' },
      { code: '10.05' },
      { code: '10.06', optional: true },
      { code: '10.08', optional: true },
      { code: '10.09', optional: true },
    ],
    tags: ['санузел', 'плитка'],
  },
  {
    title: 'Электрика: черновой этап',
    description: 'Штробление, подрозетники, кабель, электроточки, щит.',
    stage: 'engineering',
    surface: 'rooms',
    items: [
      { code: '05.01' },
      { code: '05.03' },
      { code: '05.04' },
      { code: '05.05' },
      { code: '05.07', optional: true },
    ],
    tags: ['электрика'],
  },
  {
    title: 'Электрика: чистовой этап',
    description: 'Установка механизмов, светильников, подключение.',
    stage: 'final',
    surface: 'rooms',
    items: [
      { code: '05.06' },
      { code: '05.09' },
      { code: '05.10', optional: true },
      { code: '05.11', optional: true },
    ],
    tags: ['электрика', 'чистовая'],
  },
  {
    title: 'Двери и откосы',
    description: 'Установка дверей, откосы, плинтус.',
    stage: 'final',
    surface: 'openings',
    items: [
      { code: '11.01' },
      { code: '11.02' },
      { code: '11.03' },
    ],
    tags: ['двери'],
  },
  {
    title: 'Демонтаж «под бетон»',
    description: 'Снятие покрытий, демонтаж стяжки и штукатурки, вынос мусора.',
    stage: 'demolition',
    surface: 'rooms',
    items: [
      { code: '01.01' },
      { code: '01.02' },
      { code: '01.04' },
      { code: '01.05' },
      { code: '01.11' },
      { code: '01.12' },
    ],
    tags: ['демонтаж'],
  },
];
